refactor: organize packages in a workspace
setting `jolt-sdk = { workspace = true }` in guest's dependencies will cause:

error[E0463]: can't find crate for `std`